# 1. Migrated to BC Security's version of Empire
# 2. Using Docker container - based on https://github.com/BC-SECURITY/Empire
---
- block:

  - name: 'empire : download Docker image'
    docker_image:
      name: bcsecurity/empire:latest
      source: pull

  - name: 'empire : create data container'
    docker_container:
      name: empire-data
      image: bcsecurity/empire:latest
      volumes:
        - /empire
      state: present

  - name: 'empire : create fish shell alias'
    template:
      dest: '{{ ansible_facts['env']['HOME'] }}/.config/fish/functions/empire.fish'
      mode: 0644
      src: '../templates/empire.fish'

  tags:
    - exploitation
    - empire