# TODO: switch out curl to this:
#
# - name: check sonar web is up
# uri:
#   url: http://sonarhost:9000/sonar/api/system/status
#   method: GET
#   return_content: yes
#   status_code: 200
#   body_format: json
# register: result
# until: result.json.status == "UP"
# retries: 10
# delay: 30

# TODO: add symlink
---
- block:

  - name: 'CyberChef : check existing installation'
    stat:
      path: /opt/CyberChef
    register: cyberchef_binary

  - block:
    - name: 'CyberChef : create target directory'
      file:
        path: /opt/CyberChef
        state: directory
        mode: '0755'

    - name: 'CyberChef : determine the latest version'
      uri:
        url: https://api.github.com/repos/gchq/CyberChef/releases/latest
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
      register: cyberchef_version

    - name: 'CybefChef : download and unpack binaries'
      unarchive:
        src: 'https://github.com/gchq/CyberChef/releases/download/{{ cyberchef_version.json.tag_name }}/CyberChef_{{ cyberchef_version.json.tag_name }}.zip'
        dest: /opt/CyberChef
        remote_src: yes

    - name: 'CyberChef : create a symlink to the latest version'
      file:
        src: /opt/CyberChef/CyberChef_{{ cyberchef_version.json.tag_name }}.html
        dest: /opt/CyberChef/CyberChef.html
        state: link
    when: not cyberchef_binary.stat.exists

  become: yes
  tags:
    - desktop
    - cyberchef
