---
- include: insomnia.yml tags=desktop,insomnia
- include: vscode.yml tags=desktop,vscode
- include: notable.yml tags=desktop,notable
- include: sublime.yml tags=desktop,sublime
- include: syncthing.yml tags=desktop,syncthing
- include: cyberchef.yml tags=desktop,cyberchef
- include: tweaks.yml tags=desktop,tweaks