---
- block:

  - name: 'Notable : check installation status'
    package_facts:
      manager: auto

  - name: 'Notable : download and install deb package'
    apt:
      deb: 'https://download.notable.app/?target=deb'
    when: "'notable' not in ansible_facts.packages"

  # fix for sandbox error
  - name: 'Notable : fix for sandbox error'
    file:
      path: /opt/Notable/chrome-sandbox
      owner: root
      group: root
      mode: '4755'
  
  become: yes
  tags:
    - desktop
    - notable