# TODO: CPU load indicator
# xfconf
# channel: xfce4-panel
# properties:
#   /plugins/plugin-22 => systemload
#   /panels/panel-1/plugin-ids => ???
---
- block:

  - name: 'tweaks : turn off display sleep (xfconf)'
    xfconf:
      channel: "xfce4-power-manager"
      property: "/xfce4-power-manager/dpms-enabled"
      value_type: "bool"
      value: "false"

  - name: 'tweaks : download desktop background'
    get_url:
      url: https://unsplash.com/photos/Ys-DBJeX0nE/download?force=true
      dest: ~/Pictures/background-Ys-DBJeX0nE.jpg
      mode: '0640'
        
  - name: 'tweaks : set desktop background'
    xfconf:
      channel: "xfce4-desktop"
      property: "/backdrop/screen0/monitorVirtual1/{{ item }}/last-image"
      value_type: "string"
      value: "~/Pictures/background-Ys-DBJeX0nE.jpg"
    with_items:
      - workspace0
      - workspace1

  tags:
    - desktop
    - tweaks