---
- block:

  - name: 'tweaks : turn off display sleep (xfconf)'
    xfconf:
      channel: "xfce4-power-manager"
      property: "/xfce4-power-manager/dpms-enabled"
      value_type: "bool"
      value: "false"

  - name: 'tweaks : turn off screensaver (xfconf)'
    xfconf:
      channel: "xfce4-power-manager"
      property: "/xfce4-power-manager/blank-on-ac"
      value_type: "int"
      value: 0

  - name: 'tweaks : download desktop background'
    get_url:
      url: https://unsplash.com/photos/Ys-DBJeX0nE/download?force=true
      dest: ~/Pictures/background-Ys-DBJeX0nE.jpg
      mode: '0640'
        
  - name: 'tweaks : set desktop background'
    xfconf:
      channel: "xfce4-desktop"
      property: "/backdrop/screen0/monitorVirtual1/{{ item }}/last-image"
      value_type: "string"
      value: "~/Pictures/background-Ys-DBJeX0nE.jpg"
    with_items:
      - workspace0
      - workspace1

  - name: 'tweaks : system load indicator'
    xfconf:
      channel: "xfce4-panel"
      property: "/plugins/plugin-22"
      value_type: "string"
      value: "systemload"

  - name: 'tweaks : system load indicator config'
    template:
      dest: '~/.config/xfce4/panel/systemload-22.rc'
      mode: 0640
      src: '../templates/systemload-22.rc'

  # couldn't get this to work with Ansible's xfconf module due to poor array support
  - name: 'tweaks : system load indicator posision'
    shell: 'xfconf-query -c xfce4-panel -p /panels/panel-1/plugin-ids -n -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -t int -s 1 -s 2 -s 3 -s 4 -s 5 -s 6 -s 7 -s 8 -s 9 -s 10 -s 11 -s 12 -s 13 -s 14 -s 15 -s 16 -s 17 -s 18 -s 19 -s 22 -s 20 -s 21'
  
  tags:
    - desktop
    - tweaks