---
- block:

  - name: 'pspy : check linux-binaries directory'
    file:
      path: /usr/share/linux-binaries
      state: directory
      mode: '0755'

  - name: 'pspy : check existing binaries'
    stat:
      path: /usr/share/linux-binaries/pspy64
    register: pspy_binary

  - block:

    - name: 'pspy : determine the latest version'
      shell: 'curl --silent "https://api.github.com/repos/DominicBreuker/pspy/releases/latest" | jq -r .tag_name'
      register: pspy_version

    - name: 'pspy : download binaries'
      get_url:
        url: 'https://github.com/DominicBreuker/pspy/releases/download/{{ pspy_version.stdout }}/{{ item }}'
        dest: '/usr/share/linux-binaries/{{ item }}'
        mode: '0755'
      with_items:
        - pspy32
        - pspy32s
        - pspy64
        - pspy64s
    
    when: not pspy_binary.stat.exists

  become: yes
  tags:
    - recon
    - pspy
