---
- block:

  - name: Install Docker and docker-compose
    apt:
      update_cache: yes
      name:
        - docker.io
        - docker-compose
      state: latest

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Add current user to 'docker' group
    user:
      name: {{ ansible_user_id }}
      groups: docker
      append: yes

  become: yes
  tags:
    - common
    - docker
