---
  - block:
    
    - name: 'nishang : clone repository'
      git:
        accept_hostkey: yes
        clone: yes
        depth: 1
        dest: /opt/nishang
        force: yes
        repo: https://github.com/samratashok/nishang.git
    
    become: yes
    tags:
      - exploitation
      - nishang