---
- block:

  - name: 'PayloadsAllTheThings : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/PayloadsAllTheThings
      force: yes
      repo: https://github.com/swisskyrepo/PayloadsAllTheThings.git

  become: yes
  tags:
    - exploitation
    - payloadsallthethings
