---
- block:

  - name: 'pspy : check linux-binaries directory'
    file:
      path: /usr/share/linux-binaries
      state: directory
      mode: '0755'

  - name: 'pspy : determine the latest version'
    uri:
      url: https://api.github.com/repos/DominicBreuker/pspy/releases/latest
      method: GET
      return_content: yes
      status_code: 200
      body_format: json
    register: pspy_version

  - name: 'pspy : download binaries'
    get_url:
      url: 'https://github.com/DominicBreuker/pspy/releases/download/{{ pspy_version.json.tag_name }}/{{ item }}'
      dest: '/usr/share/linux-binaries/{{ item }}'
      mode: '0755'
    with_items:
      - pspy32
      - pspy32s
      - pspy64
      - pspy64s

  become: yes
  tags:
    - recon
    - pspy
