---
- block:

  - name: 'supertty : copy Dockerfile'
    template:
      dest: '/tmp/supertty.Dockerfile'
      mode: 0644
      src: '../templates/supertty.Dockerfile'

  - name: 'supertty : build Docker image'
    docker_image:
      build:
        path: /tmp
        dockerfile: supertty.Dockerfile
      name: supertty
      source: build

  - name: 'supertty : remove Dockerfile'
    file:
      path: /tmp/supertty.Dockerfile
      state: absent

  - name: 'supertty : create fish shell alias'
    template:
      dest: '~/.config/fish/functions/supertty.fish'
      mode: 0644
      src: '../templates/supertty.fish'

  tags:
    - exploitation
    - supertty
