---
- block:

  - name: 'wpxf : install prerequisites'
    apt:
      name:
        - build-essential
        - liblzma-dev
        - libsqlite3-dev
        - patch
        - zlib1g-dev
      state: present

  - name: 'wpxf : install gem'
    shell: '/bin/bash -lc "gem install wpxf"'

  become: yes
  tags:
    - web
    - wpxf
